os: Visual Studio 2015

platform: x64

install:
  # Install rakudostar for faster CI builds.
  - choco install rakudostar
  # Install java 8 runtime
  - choco install jre8
  # Change to the build folder
  - cd %APPVEYOR_BUILD_FOLDER%
  # Refresh environment variables so that zef works
  - refreshenv

build: off

test_script:
  # Test for fun :)
  - zef install . --verbose

shallow_clone: true
